service:
  name: service-postgresql
  namespace: aicares
image:
  repository: postgres
  tag: "17.8"
containerPort: 5432
resources:
  limits:
    memory: "80Mi"
  requests:
    memory: "64Mi"
    cpu: "50m"
env: []
nodeSelector:
  eks.amazonaws.com/nodegroup: graviton-workers
